# Change these first
owner: cartelmatic # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Manager
    url: $MANAGER
  - name: Admin Baliz
    url: https://admin-baliz.cartelmatic.com/
  - name: API
    url: https://api.cartelmatic.com/APIDisponibilites/
  - name: API Auth
    url: https://api-auth.cartelmatic.com/docs
  - name: Back Office
    url: https://bo.cartelmatic.com/
  - name: Baliz
    url: https://baliz.cartelmatic.com/
  - name: Data Manager
    url: https://data-manager.cartelmatic.com/
  - name: Funbox
    url: https://funbox.cartelmatic.com/
  - name: Site Web
    url: https://www.cartelmatic.com/
  - name: V4
    url: https://v4.cartelmatic.com/ABRN01COS001FR31000/Client/index.php
  - name: Viewer
    url: https://viewer.cartelmatic.com/
  - name: VNC
    url: https://vnc.cartelmatic.com/



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img/https://www.cartelmatic.com/wp-content/uploads/2022/05/logo-cartelmatic2x.jpg
  themeurl: https://raw.githubusercontent.com/cartelmatic/upptime/master/assets/my-custom-theme.css
  name: Upptime
  introTitle: "Cartelmatic"
  introMessage: Statut global
  # theme: ocean
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
