# Change these first
owner: cartelmatic # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Manager
    url: $MANAGER
  - name: Admin Baliz
    url: https://admin-baliz.cartelmatic.com/
  - name: API
    url: https://api.cartelmatic.com/APIDisponibilites/
  - name: API Auth
    url: https://api-auth.cartelmatic.com/docs
  - name: Back Office
    url: https://bo.cartelmatic.com/
  - name: Baliz
    url: https://baliz.cartelmatic.com/
  - name: Data Manager
    url: https://data-manager.cartelmatic.com/
  - name: Funbox
    url: https://funbox.cartelmatic.com/
  - name: Site Web
    url: https://www.cartelmatic.com/
  - name: V4
    url: https://v4.cartelmatic.com/ABRN01COS001FR31000/Client/index.php
  - name: Viewer
    url: https://viewer.cartelmatic.com/
  - name: VNC
    url: https://vnc.cartelmatic.com/



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
